### ISSUE TITLE
Q: Changed the interface for modifying pool contents on the Edit Pool page

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2130] opened 2019-11-26 15:21 UTC
Version: 0.2.195

Colleagues have been asking me how to add library aliquots to an already created (but empty!) pool.
How is this intented work now?

In an empty pool I can add via `Add`. After that I have to put in (copy&paste) the library aliquot names. That is not as nice as it has been before, but probably we are simply using it the wrong way.

After that I confirm to add 1 of each aliquot (`Edit Proportions`). After clicking `Add` the window vanishes and nothing happens. The aliquots are not showing up and the UI seems to be broken:

![ui_miso](https://user-images.githubusercontent.com/1837422/69646196-ac808080-1067-11ea-904e-6d119f31812a.png)

When pressing F5 in browser, I get `This page is asking you to confirm that you want to leave - data you have entered may not be saved.`. 
In the terminal I get `JavaScript error: http://miso.molgen.mpg.de/scripts/header_script.js?version=0.2.195, line 21477: TypeError: data is null`.

- is this the "correct" way to add library aliquots to an existing pool?
- is this JavaScript error the reason for the aliquots not showing up in the pool?

**Comment by djcooke** [comment] 2019-11-26 19:54
The way that you are attempting to add library aliquots to the pool is correct. The Javascript error is the reason why aliquots are not showing up in the pool.

I was able to reproduce the error. It only happens when trying to add a library aliquot that has no indices. I will get a fix in for this for release v0.2.197.

We changed the way this worked in order to clean up the page a bit and allow you to make multiple aliquot changes without saving and reloading the page between each one. If you (or your colleagues) found the old interface more convenient, could you describe why, or how you used the old interface? Thanks!

**Comment by djcooke** [comment] 2019-11-26 20:22
#2131 will fix the issue. Should be included in release v0.2.197 as mentioned above.

If you wish to continue using v0.2.195 (and/or v0.2.196 which is also affected), adding aliquots does actually still work. After you've attempted to add aliquots, the Library Aliquots table will disappear. Hit the Save button at the top right of the page and the page will update to show the Library Aliquots again, including the one(s) you tried to add. It's not ideal, but it works.

**Comment by sklages** [comment] 2019-11-27 08:21
>  Hit the Save button at the top right of the page and the page will update to show the Library Aliquots again, including the one(s) you tried to add. It's not ideal, but it works.

Thanks. This works for a single dilution. When adding more than one dilution (without index), only the first one is saved.

**Comment by sklages** [comment] 2019-11-27 09:16
>  If you (or your colleagues) found the old interface more convenient, could you describe why, or how you used the old interface?

It was more flexible. We usually created a pool with search,tick,add :-) During pool creation there was a table showing the current pool content.

When creating a pool in current version there are two ways to do so:
- `Pools/Add/Create Pool`
Here I can add dilutions by using `Add` in the `Library Aliquots` section. I need to have some other window open to copy the `LDInnn` for pasting into the Add-popup. There is no search/select/click below (something like "available aliquots"). There is no way to see a "growing pool" (e.g when pooling 200 aliquots on a NovaSeq run), with respect to the index compatibility. When there are incompatible indices, you will get the error/warning only after saving the complete pool. Removing the aliquot with the incompatible index is easy, just remove. But adding another aliquot gives me the info about duplicate index or so very late, after saving the complete pool. 

- `Library Aliquots/Pool together`
Here I can select aliquots and pool them together. On the `Create Pools from Library Aliquots` page I do only see the pool "metadata", not the content. Again, errors concerning barcode clashes show up after saving the complete pool.

I think it's a bit of a lack of overview. We are probably simply used to do it "the old" way.

We have to deal with different index types on the same run or even on the same lane, e.g. 6nt, 8nt, 8nt-dual, pools without index in MISO (not prepared in our lab). That is why we'd like to see the pools "growing" (and to simply remove/add aliquots when hitting an index problem) :-)

We are currently not using any `Pool Orders`, not sure if this would help to create larger pools.

**Comment by djcooke** [comment] 2019-11-27 13:51
Thanks for the information. It sounds like the main issue is that you can't see the aliquots as you add them, which is due to the bug. With the bug fixed, you will see the "growing pool," including the index compatibility warnings.

I'll close this ticket for now. After you're running a version with the issue fixed, please let us know if there are still any issues

**Closed by djcooke** 2019-11-27 13:51 UTC
